version: '3.8'

volumes:
  redis_data:
    external: false
  minio_data:
    external: false
    
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      # - "${MINIO_DEV_CERT_LOCATION:?err}:/root/.minio/certs"
    env_file:
      - ./.env.minio

  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass sickmetalhead
    volumes:
      - redis_data:/data
  

  