version: '3.8'

volumes:
  geoserver_volume:
    external: false
  mongodb_volume:
    external: false
  minio_data:
    external: false
  postgres_data:
    external: false
  rabbitmq_data:
    external: false
  rabbitmq_log:
    external: false

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=accelerator
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=accelerator-native-jobs
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq
  
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - "${MINIO_DEV_CERT_LOCATION:?err}:/root/.minio/certs"
    env_file:
      - ./.env.minio

  web_be:
    build:
      context: "${PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    volumes:
      - "${PROJECT_FOLDER:?err}:/app/"
    ports:
      - 8000:8000
    env_file:
      - ./.env.web.be
    depends_on:
      - db
    
  web_fe:
    build:
      context: "${WEBCLI_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    volumes:
      - "${WEBCLI_PROJECT_FOLDER:?err}:/app/"
    ports:
      - 8080:8080
    env_file:
      - ./.env.web.fe
    depends_on:
      - web_be  
  extract_netcdf: 
    build:
      context: "${EXTRACT_NETCDF_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - "${EXTRACT_NETCDF_PROJECT_FOLDER:?err}:/app/"

  acli: 
    build:
      context: "${ACLI_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    command: sleep infinity
    volumes:
      - "${ACLI_PROJECT_FOLDER:?err}:/app/"

  celery:
    build:
      context: "${CELERY_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/accelerator-native-jobs
      - ACCELERATOR_CLI_BASE_URL=http://web_be:8000/v1/acli
    volumes:
      - "${CELERY_PROJECT_FOLDER:?err}:/app/"
    depends_on:
      - web_be
      - rabbitmq
    