volumes:
  minio_data:
    external: false
  postgres_data:
    external: false
  rabbitmq_data:
    external: false
  rabbitmq_log:
    external: false
  registry_data:
    external: false
  remark42_data:
    external: false

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=accelerator
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=accelerator-native-jobs
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - "${MINIO_DEV_CERT_LOCATION:?err}:/root/.minio/certs"
    env_file:
      - ./.env.minio

  titiler:
    build:
      context: "${TITILER_FOLDER:?err}"
      dockerfile: dockerfiles/Dockerfile.uvicorn
    platform: linux/x86_64
    ports:
      - 8002:8000
    environment:
      - PORT=8000
      - WORKERS_PER_CORE=1
      - TITILER_API_DEBUG=1
      - GDAL_HTTP_CURL_OPTIONS="CURLOPT_SSL_VERIFYPEER=0 CURLOPT_SSL_VERIFYHOST=0"


  web_be:
    build:
      context: "${PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    volumes:
      - "${PROJECT_FOLDER:?err}:/app/"
    ports:
      - 8000:8000
      - 20102:20102
    env_file:
      - ./.env.web.be
    depends_on:
      - db
      - minio
      - rabbitmq

  web_fe:
    build:
      context: "${WEBCLI_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    volumes:
      - "${WEBCLI_PROJECT_FOLDER:?err}:/app/"
    ports:
      - 8081:8081
      - 8080:8080
      - 5173:5173
    env_file:
      - ./.env.web.fe
    depends_on:
      - web_be
  # convertert:
  #   build:
  #     context: "/Users/wrufesh/iiasa/accli/example_job_folder"
  #     dockerfile: Dockerfile
  #   command: sleep infinity
  #   volumes:
  #     - "/Users/wrufesh/iiasa/accli/example_job_folder:/app/"

  acli:
    build:
      context: "${ACLI_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    command: sleep infinity
    volumes:
      - "${ACLI_PROJECT_FOLDER:?err}:/app/"

  scheduler:
    build:
      context: "${SCHEDULER_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev

    # command: sleep infinity
    privileged: true

    env_file:
      - ./.env.scheduler
    volumes:
      - "${SCHEDULER_PROJECT_FOLDER:?err}:/home/ubuntu/app/"

    depends_on:
      - web_be
      - rabbitmq
      - registry

  # image-builder-scheduler:
  #   build:
  #     context: "${SCHEDULER_PROJECT_FOLDER:?err}"
  #     # dockerfile: Dockerfile.image.builder.worker.dev
  #     dockerfile: Dockerfile.buildah

  #   # privileged: true

  #   env_file:
  #     - ./.env.scheduler
  #   volumes:
  #     - "${SCHEDULER_PROJECT_FOLDER:?err}:/home/nonroot/app/"

  #   depends_on:
  #     - web_be
  #     - rabbitmq
  #     - registry

  k8s_events:
    build:
      context: "${SCHEDULER_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.k8s.events.dev

    env_file:
      - ./.env.scheduler
    volumes:
      - "${SCHEDULER_PROJECT_FOLDER:?err}:/app/"

    depends_on:
      - web_be
      - rabbitmq

  wkubecmd:
    build:
      context: "${WKUBE_JOB_AGENT_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    environment:
      - ACC_JOB_GATEWAY_SERVER=http://web_be:8000/
      - ACC_JOB_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiSk9CIiwiY2FuX3JlZ2lzdGVyX3ZhbGlkYXRpb25fdHlwZXMiOltdLCJ1c2VyX2lkIjoxLCJqb2JfaWQiOjIzMSwiZXhwIjoxNzYzMDg2MTM5fQ.jRKBRv01t_LdqCh_qO3aPxtwdZJMLHVzSemHX8ezywc
    command: sleep infinity
    volumes:
      - "${WKUBE_JOB_AGENT_PROJECT_FOLDER:?err}:/app/"

  accms:
    build:
      context: "${ACCMS_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    ports:
      - 8001:8000
    env_file:
      - ./.env.accms
    volumes:
      - "${ACCMS_PROJECT_FOLDER:?err}:/app/"
    depends_on:
      - db


  threads:
    build:
      context: "${THREADS_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    ports:  
      - 8003:8000
    env_file:
      - ./.env.threads
    volumes:
      - "${THREADS_PROJECT_FOLDER:?err}:/app/"
    depends_on:
      - db

  registry:
    image: registry:2
    ports:
      - "5000:5000"
      - "8443:8443"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_ADDR: registry:8443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.crt
      REGISTRY_HTTP_TLS_KEY: /certs/server.key

    # Way to generate htpasswd file
    # docker run --rm --entrypoint htpasswd httpd:2 -Bbn myregistry myregistrypassword > services_docker_compose_for_dev/registry_auth/htpasswd
    volumes:
      - registry_data:/var/lib/registry
      - ./registry_auth:/auth
      - ./registry_certs:/certs

  # nginx:
  #   build:
  #     context: ../devnginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf.d/fe.nginx.conf:/etc/nginx/conf.d/fe.nginx.conf
  #     - ./nginx.conf.d/wagtail.nginx.conf:/etc/nginx/conf.d/wagtail.nginx.conf

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=defaultpassword
    ports:
      - 6379:6379
    command: "redis-server --requirepass $$REDIS_PASSWORD"

  
  accelerator_routine:
    build:
      context: "${ACCELERATOR_COMMON_ROUTINES:?err}/csv_regional_timeseries_validator"
      dockerfile: Dockerfile.dev
    command: sleep infinity
    volumes:
      - "${ACCELERATOR_COMMON_ROUTINES:?err}/csv_regional_timeseries_validator:/app/"