version: '3.8'

services:
  
  web_be:
    build:
      context: "${PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    volumes:
      - "${PROJECT_FOLDER:?err}:/app/"
    ports:
      - 8000:8000
    env_file:
      - ./.env.web.be
    # depends_on:
    #   - db
    #   - redisdb
    #   - celery_worker
  web_fe:
    build:
      context: "${WEBCLI_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    volumes:
      - "${WEBCLI_PROJECT_FOLDER:?err}:/app/"
    ports:
      - 8080:8080
    env_file:
      - ./.env.web.fe
    depends_on:
      - web_be
