apiVersion: v1
kind: Secret
metadata:
  name: accms-secret
type: Opaque
stringData:
  DEBUG: 'True'
  DATABASE_URL: "postgresql://postgres@db/accms"
  AWS_STORAGE_BUCKET_NAME: 'accms'
  AWS_ACCESS_KEY_ID: 'r0BBFaw8lzZsv4EUS'
  AWS_SECRET_ACCESS_KEY: 'lmR9CllOIncULWvqHkZTe4XJd28iwwz3Szifl'
  AWS_S3_REGION_NAME: "eu-west-1"

  AWS_S3_ADDRESSING_STYLE: "path"
  AWS_S3_ENDPOINT_URL: "https://localip:9000"
  MEDIA_URL: "https://localip:9000/accms/media/"