apiVersion: v1
kind: Secret
metadata:
  name: celery-cluster-secret
type: Opaque
stringData:
  CELERY_BROKER_URL: 'amqp://accelerator:45sdfg4sefrgtmq-pubsub-service:5672/accelerator-native-jobs'
  ACCELERATOR_CLI_BASE_URL: 'http://accelerator-be-service:8770/v1/acli'
