apiVersion: v1
kind: Secret
metadata:
  name: celery-cluster-secret
type: Opaque
stringData:
  CELERY_BROKER_URL: 'amqp://accelerator:45sdfg4sefrgtmq-pubsub-service:5672/accelerator-native-jobs'
  ACCELERATOR_CLI_BASE_URL: 'http://accelerator-be-service:8770/v1/ajob-cli'
  IMAGE_REGISTRY_URL: 'registry.iiasa.ac.at'
  IMAGE_REGISTRY_USER: 'accelerator'
  IMAGE_REGISTRY_PASSWORD: 'Th8e'
  WKUBE_K8_NAMESPACE: 'bnr-acl'
  WKUBE_SECRET_JSON_B64: 'eyJhcbHVzdGVyIn0='


