apiVersion: v1
kind: Secret
metadata:
  name: celery-cluster-secret
type: Opaque
stringData:
  CELERY_BROKER_URL: 'amqp://accelerator:45sdfg4sefrgtmq-pubsub-service:5672/accelerator-native-jobs'
  ACCELERATOR_CLI_BASE_URL: 'http://accelerator-be-service:8770'
  IMAGE_REGISTRY_URL: 'registry.iiasa.ac.at'
  IMAGE_REGISTRY_USER: 'accelerator'
  IMAGE_REGISTRY_PASSWORD: 'Th8e'
  WKUBE_K8_NAMESPACE: 'bnr-acl'
  WKUBE_SECRET_JSON_B64: 'eyJhcbHVzdGVyIn0='

  # Required for wkube image builder, wkube task dispacher and k8 event worker
  WKUBE_K8_NAMESPACE: 'bnr-acl'
  WKUBE_SECRET_JSON_B64: 'ogW3sibmFtZSI6ICJkbXpjbHVzdGVyIiwgImNsdXN0ZXIiOiB7InNlcnZlciI6ICJodHRwczdGVyIn0='

  JOBSTORE_S3_ENDPOINT: 'https://minio81.iiasa.ac.at:9000'
  JOBSTORE_S3_API_KEY: 'ac_accelerator_uat'
  JOBSTORE_S3_SECRET_KEY: 'ia5xUNh3mGh'
  JOBSTORE_S3_BUCKET_NAME: 'accelod'

  ACCELERATOR_APP_TOKEN: ''


