apiVersion: v1
kind: Secret
metadata:
  name: titiler-secret
type: Opaque
stringData:
  PORT: '8000'
  TITILER_API_CORS_ORIGINS: 'https://localhost:8080,http://localhost:8080,https://accelerator.iiasa.ac.at,https://141-iiasa-forestnavigator.vercel.app'
  FORWARDED_ALLOW_IPS: '*'
  CPL_TMPDIR: /tmp
  GDAL_CACHEMAX: '200'  # 200 mb
  VSI_CACHE: "TRUE"
  VSI_CACHE_SIZE: '5000000'  # 5 MB (per file-handle)
  GDAL_DISABLE_READDIR_ON_OPEN: "EMPTY_DIR"
  GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: "YES"
  GDAL_HTTP_MULTIPLEX: "YES"
  GDAL_HTTP_VERSION: '2'
  PYTHONWARNINGS: "ignore"

