apiVersion: v1
kind: Secret
metadata:
  name: titiler-secret
type: Opaque
stringData:
  PORT: 8000
  WORKERS_PER_CORE: 1
  TITILER_API_CORS_ORIGINS: 'https://localhost:8080,http://localhost:8080,https://accelerator.iiasa.ac.at'

