apiVersion: v1
kind: Secret
metadata:
  name: titiler-secret
type: Opaque
stringData:
  PORT: '8000'
  TITILER_API_CORS_ORIGINS: 'https://localhost:8080,http://localhost:8080,https://accelerator.iiasa.ac.at,https://141-iiasa-forestnavigator.vercel.app,https://141-iiasa-forest.vercel.app'
  FORWARDED_ALLOW_IPS: '*'

  # Temp + GDAL block cache
  CPL_TMPDIR: /tmp
  GDAL_CACHEMAX: '256'              # MB; balanced for 2 GB pods (avoid >512)
  GDAL_BAND_BLOCK_CACHE: "HASHSET"  # better for random tile reads

  # VSI caching (in-memory read buffer)
  VSI_CACHE: "TRUE"
  VSI_CACHE_SIZE: '16777216'        # 16 MB per file handle

  # HTTP / Connection pooling (S3 on HTTP/1.1)
  GDAL_DISABLE_READDIR_ON_OPEN: "EMPTY_DIR"
  GDAL_HTTP_VERSION: '1.1'
  GDAL_HTTP_MULTIPLEX: 'NO'
  GDAL_HTTP_MAX_CONNS: '128'        # per pod; total ≈ 1k across 8 pods
  GDAL_HTTP_CONNECTTIMEOUT: '30'
  GDAL_HTTP_TIMEOUT: '300'
  GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: "YES"

  # Metadata prefetching
  GDAL_INGESTED_BYTES_AT_OPEN: '32768'

  # Concurrency controls (mitigate spikes on mosaics)
  MOSAIC_CONCURRENCY: '1'
  MAX_THREADS: '1'

  # Misc
  PYTHONWARNINGS: "ignore"


