apiVersion: apps/v1
kind: Deployment
metadata:
  name: accelerator-fe
spec:
  selector:
    matchLabels:
      app: accelerator-fe
  template:
    metadata:
      labels:
        app: accelerator-fe
    spec:
      containers:
      - name: acc-be
        image: registry.iiasa.ac.at/accelerator/iiasa-acc-fe
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "1000m"
      
      
      imagePullSecrets:
        - name: iiasaregcred
---
apiVersion: v1
kind: Service
metadata:
  name: accelerator-fe-service
spec:
  type: NodePort
  selector:
    app: accelerator-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

