apiVersion: apps/v1
kind: Deployment
metadata:
  name: accelerator-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accelerator-fe
  template:
    metadata:
      labels:
        app: accelerator-fe
      annotations:
        kubernetes.io/restart-at: "2025-03-31T10:50:00+0200"
    spec:
      containers:
      - name: acc-fe
        image: registry.iiasa.ac.at/accelerator/iiasa-acc-fe:5431832
        # envFrom:
        #   - secretRef:
        #       name: accelerator-fe-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "1024Mi"
            cpu: "1000m"
      
      
      imagePullSecrets:
        - name: iiasaregcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accelerator-be
spec:
  replicas: 8
  selector:
    matchLabels:
      app: accelerator-be
  template:
    metadata:
      labels:
        app: accelerator-be
      annotations:
        kubernetes.io/restart-at: "2025-02-22T10:50:00+0200"
    spec:
      containers:
      - name: acc-be
        image: registry.iiasa.ac.at/accelerator/iiasa-acc-be:829b6e2
        envFrom:
          - secretRef:
              name: accelerator-be-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
          requests:
            memory: "1024Mi"
            cpu: "1000m"
      
      
      imagePullSecrets:
        - name: iiasaregcred
---
apiVersion: v1
kind: Service
metadata:
  name: accelerator-fe-service
spec:
  type: NodePort
  selector:
    app: accelerator-fe
  ports:
    - protocol: TCP
      port: 8880
      targetPort: 80
      nodePort: 30106
---
apiVersion: v1
kind: Service
metadata:
  name: accelerator-be-service
spec:
  type: NodePort
  selector:
    app: accelerator-be
  ports:
    - protocol: TCP
      port: 8770
      targetPort: 8000
      nodePort: 30107
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        envFrom:
          - secretRef:
              name: redis-secret
        ports:
        - containerPort: 6379
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc