apiVersion: apps/v1
kind: Deployment
metadata:
  name: accms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accms
  template:
    metadata:
      labels:
        app: accms
      annotations:
        kubernetes.io/restart-at: "2025-02-22T10:50:00+0200"
    spec:
      containers:
      - name: accms
        image: registry.iiasa.ac.at/accelerator/accms:0cd0a2f
        envFrom:
          - secretRef:
              name: accms-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2000m"
          requests:
            memory: "2048Mi"
            cpu: "2000m"

        # volumeMounts:
        #     - name: accms-media-pv
        #       mountPath: /app/media
      imagePullSecrets:
        - name: iiasaregcred
      # volumes:
      #   - name: accms-media-pv
      #     persistentVolumeClaim:
      #       claimName: accms-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: accms-service
spec:
  type: NodePort
  selector:
    app: accms
  ports:
    - protocol: TCP
      port: 8970
      targetPort: 8000
      nodePort: 30155
