apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-proxy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: minio-proxy
  template:
    metadata:
      labels:
        app: minio-proxy
    spec:
      containers:
      - name: minio-proxy
        image: registry.iiasa.ac.at/accelerator/minio-proxy
        # envFrom:
        #   - secretRef:
        #       name: accelerator-be-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "1024Mi"
            cpu: "1000m"
      
      imagePullSecrets:
        - name: iiasaregcred
---
apiVersion: v1
kind: Service
metadata:
  name: minio-proxy-service
spec:
  type: NodePort
  selector:
    app: minio-proxy
  ports:
    - protocol: TCP
      port: 8997
      targetPort: 9000
      nodePort: 30110