apiVersion: apps/v1
kind: Deployment
metadata:
  name: remark42
  labels:
    app: remark42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remark42
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: remark42
    spec:

      imagePullSecrets:
        - name: iiasaregcred
        
      containers:
        - name: remark42
          image: registry.iiasa.ac.at/accelerator/remark42:v1.14.0
          ports:
            # http:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: remark42-secret
          volumeMounts:
            - name: srvvar
              mountPath: /srv/var
          securityContext:
            readOnlyRootFilesystem: false
          resources:
            requests:
              cpu: "100m"
              memory: "25Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
        - name: sync-s3
          image: registry.iiasa.ac.at/accelerator/aws-cli:latest
          command: ["sh", "-c", "while true; do aws s3 sync /srv/var s3://remark42-iiasa --delete; sleep 86400; done"]

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: remark42-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: remark42-secret
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "25Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: srvvar
              mountPath: /srv/var
      # securityContext:
        # Has its own root privilege drop. Can't do runAsUser / runAsGroup.
      volumes:
        - name: srvvar
          persistentVolumeClaim:
            claimName: remark42-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: remark42-web
spec:
  type: NodePort
  selector:
    app: remark42
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30154