apiVersion: apps/v1
kind: Deployment
metadata:
  name: titiler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: titiler
  template:
    metadata:
      labels:
        app: titiler
    spec:
      containers:
      - name: titiler
        image: registry.iiasa.ac.at/accelerator/titiler:latest
        envFrom:
          - secretRef:
              name: titiler-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "4095Mi"
            cpu: "4000m"
          requests:
            memory: "4095Mi"
            cpu: "4000m"
---
apiVersion: v1
kind: Service
metadata:
  name: titiler-service
spec:
  type: NodePort
  selector:
    app: titiler
  ports:
    - protocol: TCP
      port: 8798
      targetPort: 8000
      nodePort: 30135

